### ISSUE TITLE
denops die suddenly and could not alive by itself

### ISSUE THREAD

**Issue by lambdalisue** [vim-denops/denops.vim#184]
```
Error detected while processing function gin#action#fn[3]..<lambda>1184[1]..<SNR>410_edit[6]..<lambda>1188[1]..<SNR>101_command[4]..denops#request[1]..denops#server#request[6]..<SNR>248_request:
line    1:
Error invoking 'invoke' on channel 7:
Invalid channel: 7
[denops] Error: Failed to call 'command' with [["commit","-v"]]: Error: Failed to call 'batch' with [["denops#api#cmd","echohl ErrorMsg",{}],["denops#api#cmd","redraw | echo message",{"message":"[gin]: Failed to call 'call' with [\"denops#api#cmd\",\"do <nomodeline> User GinCommandPost\",{}]: SessionClosedError: The session is closed\n    at Session.close (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:179:31)\n    at Session.dispose (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:171:10)\n    at Neovim.dispose (file:///Users/alisue/ghq/github.com/vim-denops/denops.vim/denops/@denops-private/host/nvim.ts:58:19)\n    at using (https://deno.land/x/disposable@v1.0.2/using.ts:16:20)\n    at async file:///Users/alisue/ghq/github.com/vim-denops/denops.vim/denops/@denops-private/cli.ts:30:3"}],["denops#api#cmd","echohl None",{}]]: SessionClosedError: The session is closed
[denops]     at Session.call (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:195:13)
[denops]     at Neovim.batch (file:///Users/alisue/ghq/github.com/vim-denops/denops.vim/denops/@denops-private/host/nvim.ts:29:44)
[denops]     at Service.batch (file:///Users/alisue/ghq/github.com/vim-denops/denops.vim/denops/@denops-private/service.ts:92:29)
[denops]     at Session.batch (file:///Users/alisue/ghq/github.com/vim-denops/denops.vim/denops/@denops-private/service.ts:140:28)
[denops]     at Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:99:42)
[denops]     at https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:108:29
[denops]     at Session.handleRequest (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:114:7)
[denops]     at Session.listen (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:148:16)
[denops]     at Session.call (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:207:13)
[denops]     at async DenopsImpl.batch (file:///Users/alisue/ghq/github.com/vim-denops/denops.vim/denops/@denops/impl.ts:35:31)
[denops]     at async batch (https://deno.land/x/denops_std@v3.3.0/batch/batch.ts:94:3)
[denops]     at async echoerr (https://deno.land/x/denops_std@v3.3.0/helper/echo.ts:33:3)
[denops]     at async Module.friendlyCall (https://deno.land/x/denops_std@v3.3.0/helper/echo.ts:57:7)
[denops]     at async Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:99:12)
[denops]     at async https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:108:18
[denops]     at async Session.handleRequest (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:104:29)
[denops]     at Session.call (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:207:13)
[denops]     at async Service.dispatch (file:///Users/alisue/ghq/github.com/vim-denops/denops.vim/denops/@denops-private/service.ts:101:14)
[denops]     at async Session.invoke (file:///Users/alisue/ghq/github.com/vim-denops/denops.vim/denops/@denops-private/host/nvim.ts:48:16)
[denops]     at async Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:99:12)
[denops]     at async Session.handleNotification (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:130:7)
```

I needed to restart denops manually with

```
call denops#server#restart()
```

**Comment by lambdalisue** [comment]
I could not reproduce it anymore so close.
