### ISSUE TITLE
Denops v5 shows almost all errors as "unknown error" only

### ISSUE THREAD

**Issue by lambdalisue** [vim-denops/denops.vim#259]
Difference between calling `InvokeError` command result on https://github.com/vim-denops/denops-error-test.vim

#### v4

```
Error detected while processing function denops#request[1]..denops#server#request[4]..denops#_internal#server#chan#request[4]..denops#_internal#rpc#nvim#request:
line    1:
Error invoking 'invoke' on channel 8:
Error: Failed to call 'error' with []: Error: This is error from denops-error-test.vim
    at Session.error (file:///Users/alisue/ghq/github.com/vim-denops/denops-error-test.vim/denops/error-test/main.ts#62.92325:6:13)
    at Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:99:42)
    at https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:108:29
    at Session.handleRequest (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:114:5)
    at Session.listen (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:148:16)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async file:///Users/alisue/ghq/github.com/vim-denops/denops.vim/denops/@denops-private/worker/script.ts:85:9
    at async using (https://deno.land/x/disposable@v1.1.1/using.ts:14:12)
    at async main (file:///Users/alisue/ghq/github.com/vim-denops/denops.vim/denops/@denops-private/worker/script.ts:26:3)
    at Session.call (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:207:13)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async Service.dispatch (file:///Users/alisue/ghq/github.com/vim-denops/denops.vim/denops/@denops-private/service.ts:117:14)
    at async Session.invoke (file:///Users/alisue/ghq/github.com/vim-denops/denops.vim/denops/@denops-private/host/nvim.ts:57:16)
    at async Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:99:12)
    at async https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:108:18
    at async Session.handleRequest (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:104:29)
```

#### v5

```
Error detected while processing function denops#request[1]..denops#server#request[4]..denops#_internal#server#chan#request[4]..denops#_internal#rpc#nvim#request:
line    1:
Error invoking 'invoke' on channel 8:
unknown error
```

**Comment by lambdalisue** [comment]
It seems to be a bug caused by serialization in deno-messagepack-rpc.

**Comment by lambdalisue** [comment]
It seems Neovim does not support arbitrary error object.
https://github.com/neovim/neovim/blob/b8a2220f5eb32ead6b66f7c49b7e915883bf3539/src/nvim/msgpack_rpc/channel.c#L213-L236
