### ISSUE TITLE
Can't get value from getbufinfo() if Funcref local variable is defined in Vim

### ISSUE THREAD

**Issue by holliy** [vim-denops/denops.vim#263]
When getting getbufinfo() from Vim, an error occurs because Funcref cannot be converted.

main.ts
```typescript
import { Denops } from "https://deno.land/x/denops_std@v5.0.1/mod.ts";
import { execute } from "https://deno.land/x/denops_std@v5.0.1/helper/mod.ts";
import * as fn from "https://deno.land/x/denops_std@v5.0.1/function/mod.ts";

export async function main(denops: Denops): Promise<void> {
  await execute(denops, 'let b:f = function("abs")');
  console.log(await fn.getbufinfo(denops));
}
```

```
[denops] Spawn server [1/4]
[denops] Server started: ['deno', 'run', '-q', '...cli.ts', '--quiet', '--identity', '--port', '0']
[denops] Server listen: 127.0.0.1:45745
[denops] Connecting to channel `127.0.0.1:45745` [1/4]
[denops] Channel connected (127.0.0.1:45745)
[denops] DenopsReady
[denops] 1 plugins are discovered
[denops] register plugin: ['test', '/home/name/w...ebug', 'version': '9.0.1657'}, {'mode': 'skip'}]
[denops] (test) Error: Failed to call 'getbufinfo()': Vim(call):E1161: Cannot json encode a func
[denops] function denops#api#vim#call, line 5
[denops]     at Vim.call (file:///home/name/.vim...ps.vim/denops/@denops-private/host/vim.ts:34:13)
[denops]     at eventLoopTick (ext:core/01_core.js:182:11)
[denops]     at async Object.call (file:///home/...ps.vim/denops/@denops-private/service.ts:164:14)
[denops]     at async dispatch (https://deno.land/x/messagepack_rpc@v2.0.0/dispatcher.ts:36:12)
[denops]     at async Session.#dispatch (https:/...land/x/messagepack_rpc@v2.0.0/session.ts:244:22)
[denops]     at async Session.#handleRequestMess...nd/x/messagepack_rpc@v2.0.0/session.ts:271:33) {
[denops]   name: "Error"
[denops] }
```

In Neovim, Funref is converted as null.
```
[denops] Spawn server [1/4]
[denops] Server started: ['deno', 'run', '...s', '--quiet', '--identity', '--port', '0']
[denops] Server listen: 127.0.0.1:38437
[denops] Connecting to channel `127.0.0.1:38437` [1/4]
[denops] Channel connected (127.0.0.1:38437)
[denops] DenopsReady
[denops] 1 plugins are discovered
[denops] register plugin: ['test', '/home/...g', 'version': '0.10.0'}, {'mode': 'skip'}]
[denops] (test) [
[denops]   {
[denops]     lnum: 1,
[denops]     bufnr: 1,
[denops]     variables: { changedtick: 2, f: null },
[denops]     name: "",
[denops]     changed: false,
[denops]     lastused: 1687599463,
[denops]     loaded: true,
[denops]     windows: [ 1000 ],
[denops]     hidden: false,
[denops]     listed: true,
[denops]     changedtick: 2,
[denops]     linecount: 1
[denops]   }
[denops] ]
```

Environments:
* Vim: 9.0.1657
* deno: 1.34.0
* denops.vim: df65c22
* (Neovim: v0.10.0-dev-569+gfa0a25dcb)

**Comment by lambdalisue** [comment]
Unfortunately, there is nothing we can do on the denops side because this is happening in Vim's RPC, so we need to add some processing on the Vim side, such as replacing funcref etc. with null in RPC.
