### ISSUE TITLE
Sometimes connection closed by channel error

### ISSUE THREAD

**Issue by kuuote** [vim-denops/denops.vim#268]
# Problem

Connection closed by `ch 4 returned a response with an unknown request id. Ensure the client is properly synchronized` in some case

# To Repoduce

1. introduce following plugins

https://github.com/vim-denops/denops.vim/commit/fece0a2b24655e42a3fd10dbbf2962d39b381e90
https://github.com/vim-skk/skkeleton/commit/d31549c3ee7d0aa3331b3cdd34e0681bdacc486c

2. introduce init.vim

```vim
set rtp+=/path/to/vim-denops/denops.vim
set rtp+=/path/to/vim-skk/skkeleton

autocmd User DenopsPluginPost:skkeleton call skkeleton#initialize()
autocmd User skkeleton-initialize-pre call skkeleton#config({})
nnoremap i i<Plug>(skkeleton-enable)<Esc>
sleep 500m
```

3. Launch Neovim (HEAD or Stable 0.9.1)

`nvim --clean -u init.vim`

4. press `i` immediately

# Screen Shot

![Screenshot_20230719-125225](https://github.com/vim-denops/denops.vim/assets/36663503/e7099203-d3db-4c8f-a44a-8f139ba9673d)

**Comment by kuuote** [comment]
skkeleton無しでの再現手順は後ほど用意します

**Comment by kuuote** [comment]
```
調査用ログ

 [denops] (skkeleton) SENT [
 [denops]   0,
 [denops]   0,
 [denops]   "call",
 [denops]   [
 [denops]     "denops#api#cmd",
 [denops]     "doautocmd <nomodeline> User DenopsSystemPluginPre:skkeleton",
 [denops]     {}
 [denops]   ]
 [denops] ]
 [denops] (skkeleton) RECV [ 1, 0, null, 0 ]
 [denops] (skkeleton) SENT [
 [denops]   0,
 [denops]   1,
 [denops]   "call",
 [denops]   [
 [denops]     "denops#api#eval",
 [denops]     "exists(n) ? g:skkeleton#debug : v",
 [denops]     { n: "g:skkeleton#debug", v: false }
 [denops]   ]
 [denops] ]
 [denops] (skkeleton) RECV [ 1, 1, null, false ]
 [denops] (skkeleton) SENT [
 [denops]   0,
 [denops]   2,
 [denops]   "call",
 [denops]   [
 [denops]     "denops#api#cmd",
 [denops]     "doautocmd <nomodeline> User DenopsSystemPluginPost:skkeleton",
 [denops]     {}
 [denops]   ]
 [denops] ]
 Error detected while processing function skkeleton#handle[1]..skkeleton#request[4]..denops#request[1]..denops#server#request[4]..denops#_internal#server#chan#request[4]..denops#_internal#rpc#nvim#request:
 line    1:
 Error invoking 'invoke' on channel 4:
 ch 4 returned a response with an unknown request id. Ensure the client is properly synchronized
 Error detected while processing function skkeleton#handle[1]..skkeleton#request[4]..denops#request[1]..denops#server#request[4]..denops#_internal#server#chan#request[4]..denops#_internal#rpc#nvim#request:
 line    1:
 Error invoking 'invoke' on channel 4:
 Invalid channel: 4
 Error detected while processing function skkeleton#handle[1]..skkeleton#request[4]..denops#request[1]..denops#server#request[4]..denops#_internal#server#chan#request[4]..denops#_internal#rpc#nvim#request:
 line    1:
 Error invoking 'invoke' on channel 4:
 Invalid channel: 4
 Error detected while processing function skkeleton#handle[1]..skkeleton#request[4]..denops#request[1]..denops#server#request[4]..denops#_internal#server#chan#request[4]..denops#_internal#rpc#nvim#request:
 line    1:
 Error invoking 'invoke' on channel 4:
 Invalid channel: 4
 [denops] (skkeleton) RECV [ 0, 0, "initialize", [] ]
 [denops] (skkeleton) SENT [
 [denops]   0,
 [denops]   3,
 [denops]   "call",
 [denops]   [
 [denops]     "denops#api#cmd",
 [denops]     "doautocmd <nomodeline> User skkeleton-initialize-pre",
 [denops]     {}
 [denops]   ]
 [denops] ]
 [denops] (skkeleton) RECV [
 [denops]   0,
 [denops]   1,
 [denops]   "enable",
 [denops]   [
 [denops]     {},
 [denops]     {
 [denops]       prevInput: "",
 [denops]       completeInfo: { pum_visible: 0, mode: "", selected: -1, items: [] },
 [denops]       mode: "i",
 [denops]       completeType: "native"
 [denops]     }
 [denops]   ]
 [denops] ]
 [denops] (skkeleton) SENT [
 [denops]   0,
 [denops]   4,
 [denops]   "call",
 [denops]   [
 [denops]     "denops#api#cmd",
 [denops]     "doautocmd <nomodeline> User skkeleton-initialize-pre",
 [denops]     {}
 [denops]   ]
 [denops] ]
 [denops] (skkeleton) RECV [ 1, 2, null, 0 ]
 [denops] (skkeleton) RECV [ 0, 2, "config", [ {} ] ]
 [denops] (skkeleton) SENT [ 1, 2, null, undefined ]
 [denops] (skkeleton) RECV [ 0, 3, "config", [ {} ] ]
 [denops] (skkeleton) SENT [ 1, 3, null, undefined ]
 [denops] Unexpected error Error: Session is not running
 [denops]     at Session.shutdown (https://deno.land/x/messagepack_rpc@v2.0.1/session.ts:212:13)
 [denops]     at Neovim.dispose (file:///Users/alisue/ghq/github.com/vim-denops/denops.vim/denops/@denops-private/host/nvim.ts:77:19)
 [denops]     at using (https://deno.land/x/disposable@v1.1.1/using.ts:16:20)
 [denops]     at eventLoopTick (ext:core/01_core.js:183:11)
 [denops]     at async handleConn (file:///Users/alisue/ghq/github.com/vim-denops/denops.vim/denops/@denops-private/cli.ts:37:3)
```

**Comment by kuuote** [comment]
https://github.com/kuuote/denops-issue-268
こちらを使えばskkeleton無しで再現できると思います

**Comment by Shougo** [comment]
It seems neovim's bug.

```diff
@@ -321,26 +319,32 @@ static void parse_msgpack(Channel *channel)
       }
       arena_mem_free(arena_finish(&p->arena));
     } else if (p->type == kMessageTypeResponse) {
-      ChannelCallFrame *frame = kv_last(channel->rpc.call_stack);
-      if (p->request_id != frame->request_id) {
-        char buf[256];
-        snprintf(buf, sizeof(buf),
-                 "ch %" PRIu64 " returned a response with an unknown request "
-                 "id. Ensure the client is properly synchronized",
-                 channel->id);
-        chan_close_with_error(channel, buf, LOGLVL_ERR);
+      size_t size = kv_size(channel->rpc.call_stack);
+      for (size_t i = 0; i < size; i++) {
+        ChannelCallFrame *frame = kv_Z(channel->rpc.call_stack, i);
+        if (frame->returned) {
+          continue;
+        }
+        if (frame->request_id == p->request_id) {
+          frame->returned = true;
+          frame->errored = (p->error.type != kObjectTypeNil);
+          if (frame->errored) {
+            frame->result = p->error;
+            // TODO(bfredl): p->result should not even be decoded
+            // api_free_object(p->result);
+          } else {
+            frame->result = p->result;
+          }
+          frame->result_mem = arena_finish(&p->arena);
+          goto end;
+        }
       }
-      frame->returned = true;
-      frame->errored = (p->error.type != kObjectTypeNil);
-
-      if (frame->errored) {
-        frame->result = p->error;
-        // TODO(bfredl): p->result should not even be decoded
-        // api_free_object(p->result);
-      } else {
-        frame->result = p->result;
-      }
-      frame->result_mem = arena_finish(&p->arena);
+      char buf[256];
+      snprintf(buf, sizeof(buf),
+               "ch %" PRIu64 " returned a response with an unknown request "
+               "id. Ensure the client is properly synchronized",
+               channel->id);
+      chan_close_with_error(channel, buf, LOGLVL_ERR);
     } else {
       log_client_msg(channel->id, p->type == kMessageTypeRequest, p->handler.name);
 
@@ -353,6 +357,7 @@ static void parse_msgpack(Channel *channel)
       handle_request(channel, p, arg);
     }
   }
+end:
 
   if (unpacker_closed(p)) {
     chan_close_with_error(channel, p->unpack_error.msg, LOGLVL_ERR);
@@ -361,8 +366,7 @@ static void parse_msgpack(Channel *channel)
 }
```

**Comment by lambdalisue** [comment]
https://github.com/vim-denops/denops-issue268
