### ISSUE TITLE
Server stops over 3 times due to the module's source code could not be parsed error.

### ISSUE THREAD

**Issue by takavfx** [vim-denops/denops.vim#356]
## Issue

Denops server outputs errros and the server stops over 3 times.
The is like below

```
[denops] error: Uncaught (in worker "127.0.0.1:52079") The module's source code could not be parsed: Expected ';', '}' or <eof> at file:///C:/Users/aurat/AppData/Local/nvim-data/lazy/denops.vim/denops/@denops-private/worker.ts:45:15
[denops] 
[denops]     await using host = new hostCtor(reader, writer);
[denops]                 ~~~~
[denops] error: Uncaught (in promise) Error: Unhandled error in child worker.
[denops]     at Worker.#pollControl (ext:runtime/11_workers.js:157:19)
[denops] Server stopped (1). Restarting...
[denops] error: Uncaught (in worker "127.0.0.1:52085") The module's source code could not be parsed: Expected ';', '}' or <eof> at file:///C:/Users/aurat/AppData/Local/nvim-data/lazy/denops.vim/denops/@denops-private/worker.ts:45:15
[denops] 
[denops]     await using host = new hostCtor(reader, writer);
[denops]                 ~~~~
[denops] error: Uncaught (in promise) Error: Unhandled error in child worker.
[denops]     at Worker.#pollControl (ext:runtime/11_workers.js:157:19)
[denops] Server stopped (1). Restarting...
[denops] error: Uncaught (in worker "127.0.0.1:52087") The module's source code could not be parsed: Expected ';', '}' or <eof> at file:///C:/Users/aurat/AppData/Local/nvim-data/lazy/denops.vim/denops/@denops-private/worker.ts:45:15
[denops] 
[denops]     await using host = new hostCtor(reader, writer);
[denops]                 ~~~~
[denops] error: Uncaught (in promise) Error: Unhandled error in child worker.
[denops]     at Worker.#pollControl (ext:runtime/11_workers.js:157:19)
[denops] Server stopped 3 times within 10000 millisec. Denops is disabled to avoid infinity restart loop.
```

## Environment

OS: Windows 11 Pro 23H3
NeoVim Version: v0.10.0
Build type: Release

## Reporduce

1. Create clean LazyVim environemnt (without any plugins)
2. Set installation settings with lua file like below

```lua/plugins/denops.lua
return {
  { "vim-denops/denops.vim" }
}
```

**Comment by Shougo** [comment]
Well, please test it without LazyVim.

**Comment by Milly** [comment]
Please write the version of `deno.exe`.

**Comment by takavfx** [comment]
deno version is 1.31.2 (release, x86_64-pc-windows-msvc)

**Comment by takavfx** [comment]
I upgraded deno to 1.44.0 and the fix the error. Sorry for making a noise 🫣
I'll close this issue. Thank you.

**Comment by a24hori** [comment]
I use deno ver.2.5.0 (latest as of 2025/09/16) and the same error is produced.

```
[denops] error: Uncaught (in promise) Error: Unhandled error in child worker.
[denops]     at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
[denops]     at eventLoopTick (ext:core/01_core.js:179:7)
[denops] Server stopped (1). Restarting...
[denops] error: Uncaught (in worker "127.0.0.1:56660") TypeError: callback is not a function
[denops]     at ext:deno_node/_fs/_fs_close.ts:17:5
[denops]     at callback (ext:deno_web/02_timers.js:58:7)
[denops]     at eventLoopTick (ext:core/01_core.js:214:13)
[denops] error: Uncaught (in promise) Error: Unhandled error in child worker.
[denops]     at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
[denops]     at eventLoopTick (ext:core/01_core.js:179:7)
[denops] Server stopped (1). Restarting...
[denops] error: Uncaught (in worker "127.0.0.1:57240") TypeError: callback is not a function
[denops]     at ext:deno_node/_fs/_fs_close.ts:17:5
[denops]     at callback (ext:deno_web/02_timers.js:58:7)
[denops]     at eventLoopTick (ext:core/01_core.js:214:13)
[denops] error: Uncaught (in promise) Error: Unhandled error in child worker.
[denops]     at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
[denops]     at eventLoopTick (ext:core/01_core.js:179:7)
[denops] Server stopped (1). Restarting...
[denops] error: Uncaught (in worker "127.0.0.1:46070") TypeError: callback is not a function
[denops]     at ext:deno_node/_fs/_fs_close.ts:17:5
[denops]     at callback (ext:deno_web/02_timers.js:58:7)
[denops]     at eventLoopTick (ext:core/01_core.js:214:13)
[denops] error: Uncaught (in promise) Error: Unhandled error in child worker.
[denops]     at Worker.#pollControl (ext:runtime/11_workers.js:204:19)                                                  [denops]     at eventLoopTick (ext:core/01_core.js:179:7)                                                               [denops] Server stopped 4 times within 10000 millisec. Denops is disabled to avoid infinity restart loop.
```

**Environment**
- OS: WSL (Ubuntu 24.04)
- NeoVim Version: v0.11.4
- Build type: Release

**Comment by lambdalisue** [comment]
@a24hori It's not same but duplicated with #460
