### ISSUE TITLE
Error when starting Skkeleton

### ISSUE THREAD

**Issue by uhooi** [vim-denops/denops.vim#372]
### Describe the bug

When Neovim starts:

```
[denops]     at file:///Users/uhooi/.local/share/nvim/lazy/skkeleton/denops/skkeleton/deps/std/path.ts:1:15
```

When Skkeleton starts:

```
Error invoking 'invoke' on channel 4 (denops):
TypeError: this[#denops].dispatcher[fn] is not a function
    at Plugin.call (file:///Users/uhooi/.local/share/nvim/lazy/denops.vim/denops/@denops-private/service.ts:176:45)
    at Service.#dispatch (file:///Users/uhooi/.local/share/nvim/lazy/denops.vim/denops/@denops-private/service.ts:88:25)
    at Service.dispatch (file:///Users/uhooi/.local/share/nvim/lazy/denops.vim/denops/@denops-private/service.ts:93:34)
    at invoke (file:///Users/uhooi/.local/share/nvim/lazy/denops.vim/denops/@denops-private/host.ts:78:22)
    at Object.invoke (file:///Users/uhooi/.local/share/nvim/lazy/denops.vim/denops/@denops-private/host/nvim.ts:31:16)
    at dispatch (https://deno.land/x/messagepack_rpc@v2.0.3/dispatcher.ts:36:36)
    at Session.#dispatch (https://deno.land/x/messagepack_rpc@v2.0.3/session.ts:244:28)
    at Session.#handleRequestMessage (https://deno.land/x/messagepack_rpc@v2.0.3/session.ts:271:53)
    at Session.#handleMessage (https://deno.land/x/messagepack_rpc@v2.0.3/session.ts:255:37)
    at Object.write (https://deno.land/x/messagepack_rpc@v2.0.3/session.ts:159:63)
```

### Provide a minimal vimrc with less than 50 lines to reproduce

```vim
' TODO
```

### How to reproduce the problem from Vim startup

None.

### Expected behavior

Skkeleton starts without error.

### Actual behavior

Error when starting Skkeleton.

### Screenshots (if need)

None.

### Your environment

- OS: `uname -a` (macOS/Linux) or `ver` (Windows)  
  ```bash
  $ uname -a
  Darwin uhooinoMacBook-Air.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 arm64 arm Darwin
  ```
- Deno version: `deno --version`  
  ```bash
  $ deno --version
  deno 1.38.2 (release, aarch64-apple-darwin)
  v8 12.0.267.1
  typescript 5.2.2
  ```
- Vim/Neovim version: `vim --version` or `nvim --version`  
  ```bash
  $ nvim --version
  NVIM v0.11.0-dev-302+gbe999e6a0
  Build type: Release
  LuaJIT 2.1.1716656478
  Run "nvim -V1 -v" for more info
  ```
- Denops version: `git log -1` (run in the denops.vim repository)  
  ```bash
  $ git log -1
  commit d196190ff2efd5efca38b0170c23155bdbd71f9d (HEAD -> main, tag: v6.0.9, origin/main, origin/HEAD)
  Merge: c6fa7c6 54f3953
  Author: Λlisue (Ali sue・ありすえ) <lambdalisue@gmail.com>
  Date:   Sat Jun 22 13:32:29 2024 +0900
  
      Merge pull request #370 from vim-denops/fix_typo
  
      Fix typo
  ```

### Additional context

None

**Comment by lambdalisue** [comment]
@uhooi Could you try https://github.com/vim-denops/denops.vim/pull/374 and rewrite the error message on PR?

**Comment by uhooi** [comment]
@lambdalisue New error.

It was on toggle, not on startup :pray:

```bash
[denops] Failed to load plugin 'skkeleton': TypeError: Could not find version of '@std/path' that matches specified version constraint '0.225.2'
[denops]     at file:///Users/uhooi/.local/share/nvim/lazy/skkeleton/denops/skkeleton/deps/std/path.ts:1:15
Too many errors. Disabling Noice
Error detected while processing function skkeleton#handle[1]..skkeleton#request[2]..denops#request[1]..denops#_internal#server#chan#request[6]..denops#_intern
al#rpc#nvim#request:
line    1:
Error invoking 'invoke' on channel 4 (denops):
Error: Failed to call handle("toggle", {}, {"prevInput":"","completeInfo":{"pum_visible":0,"mode":"","selected":-1,"items":[]},"mode":"i","completeType":"nati
ve"}) in skkeleton: this[#denops].dispatcher[fn] is not a function
    at Plugin.call (file:///Users/uhooi/.local/share/nvim/lazy/denops.vim/denops/@denops-private/service.ts:181:13)
    at Service.#dispatch (file:///Users/uhooi/.local/share/nvim/lazy/denops.vim/denops/@denops-private/service.ts:88:25)
    at Service.dispatch (file:///Users/uhooi/.local/share/nvim/lazy/denops.vim/denops/@denops-private/service.ts:93:34)
    at invoke (file:///Users/uhooi/.local/share/nvim/lazy/denops.vim/denops/@denops-private/host.ts:78:22)
    at Object.invoke (file:///Users/uhooi/.local/share/nvim/lazy/denops.vim/denops/@denops-private/host/nvim.ts:31:16)
    at dispatch (https://deno.land/x/messagepack_rpc@v2.0.3/dispatcher.ts:36:36)
    at Session.#dispatch (https://deno.land/x/messagepack_rpc@v2.0.3/session.ts:244:28)
    at Session.#handleRequestMessage (https://deno.land/x/messagepack_rpc@v2.0.3/session.ts:271:53)
    at Session.#handleMessage (https://deno.land/x/messagepack_rpc@v2.0.3/session.ts:255:37)
    at Object.write (https://deno.land/x/messagepack_rpc@v2.0.3/session.ts:159:63)
```

**Comment by lambdalisue** [comment]
@uhooi Not sure but it seems the reason is same with https://github.com/vim-denops/denops.vim/issues/358. Could you try `:call denops#cache#update(#{reload: v:true})`?

**Comment by uhooi** [comment]
@lambdalisue 
I ran the command and it fixed it.
Thank you.
